#ifndef X86_CONFIG_H_INCLUDED
#define X86_CONFIG_H_INCLUDED

// x86 Configuration Header for XBE Recompilation
// This file is generated by XenonRecomp and should be included before x86_context.h

// Image configuration - these will be set by the recompiler
#ifndef X86_IMAGE_BASE
#define X86_IMAGE_BASE 0x10000
#endif

#ifndef X86_IMAGE_SIZE
#define X86_IMAGE_SIZE 0x1000000
#endif

#ifndef X86_CODE_BASE
#define X86_CODE_BASE 0x10000
#endif

// Stack configuration
#ifndef X86_STACK_BASE
#define X86_STACK_BASE 0x80000000
#endif

#ifndef X86_STACK_SIZE
#define X86_STACK_SIZE 0x100000
#endif

// Xbox Original specific constants
// Xbox has 64MB of RAM
#define XBOX_RAM_SIZE 0x4000000

// Xbox kernel base address (XBOXKRNL.EXE)
#define XBOX_KERNEL_BASE 0x80010000

// Xbox TLS (Thread Local Storage) typically accessed via FS segment
// FS:[0x00] = Current SEH frame
// FS:[0x04] = Stack base
// FS:[0x08] = Stack limit
// FS:[0x1C] = Self pointer (TEB)
// FS:[0x28] = Process ID
// FS:[0x2C] = Thread ID

// Optimization flags - enable only after verifying correctness
// #define X86_CONFIG_SKIP_EFLAGS_UPDATE  // Skip unnecessary flag updates
// #define X86_CONFIG_LOCAL_STACK_FRAME   // Use host stack for local variables

#endif // X86_CONFIG_H_INCLUDED
